version: "3.8"

services:
  app:
    image: ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
    container_name: node-app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: "production"
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    restart: always
